### ISSUE TITLE
ERROR:  could not identify an equality operator for type lquery

### ISSUE THREAD

**Issue by maipeng** [mla/pg_sample#17]
Hello,
Last version of pg_sample.
I've got this error:
DBD::Pg::db do failed: ERROR:  could not identify an equality operator for type lquery
LINE 3:            SELECT DISTINCT t1.*
                                   ^ at ./pg_sample line 296.
	main::__ANON__("DBD::Pg::db do failed: ERROR:  could not identify an equality"..., DBI::db=HASH(0x5604c5186bc0), undef) called at ./pg_sample line 644
command:
`./pg_sample -U user database --limit="test.user = 1000, test.user=active,test.user_has_action = 100000,test.user_has_review = 10000 ,test.entity_has_comment=10000, test.user_has_rating=100000, date.* = *, comp.* = *"   | psql -U user dbsample
`
thanks for your help.

**Comment by mla** [comment]
Hello @maipeng!

Is your db using the "ltree" extension? https://www.postgresql.org/docs/9.6/ltree.html

I am not familiar with it, but it says:
"lquery represents a regular-expression-like pattern for matching ltree values."

So I guess when pg_sample is trying to find unique rows, it's failing because there's an equality operator defined on lquery type. Do you need that table in the sample?

It looks like it's equiv to this example:
https://stackoverflow.com/questions/48420438/postgresql-could-not-identify-an-equality-operator-for-type-json

So if you need it in the sample, we need to figure out how to define an equality operator on it, or a way to exclude that particular column.

**Comment by maipeng** [comment]
Hello @mla,
thanks for the answer, finally I've found a workaround: alter the column into text before using pg_sample, then alter to lquery at the end.

**Comment by AdityaAnand1** [comment]
> alter the column into text before using pg_sample

Is there a better solution? It's not very feasible to manually change column types just to use this.

**Comment by mla** [comment]
Are you also using the ltree extension?

We need some way to compare values. If that's not possible, then I think the only alternative is to figure out a way to exclude that data entirely (or include it all).

**Comment by AdityaAnand1** [comment]
For me, simple json field is also not working.
