### ISSUE TITLE
Docker workflow

### ISSUE THREAD

**Issue by olivierdalang** [mla/pg_sample#27]
Hi !

Thanks for the library, works really well (from the dev branch).

In the dockerfile, instead of
```
ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
```
you could have
```
ENTRYPOINT ["pg_sample"]
```

This way it's easier to run, in just one command, without having to create a named container.

```
docker build -t pg_sample . 
docker run -it --rm --network=host -v "$(PWD):/io" --entrypoint="" pg_sample mydb --host=127.0.0.1 --username=postgres --password=postgres --file /io/output.sql --limit="* = 5" --data-only
```

Additionally, configuring auto-build on dockerhub is super-easy, and that would even avoid having to checkout/build the dockerfile locally.

If you're willing to accept this changes, I can prepare a PR.

**Comment by mla** [comment]
Yes, please do. Thank!

**Comment by mla** [comment]
Thank you @olivierdalang. It seems I need to qualify as an open-source project to get dockerhub auto build permission.
Will do that.

In the meantime, I've pushed out a release with queued up fixes. And we'll get this out next.

**Comment by mla** [comment]
Looks like they recently disabled the autobuild for free tier:
https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

I started the open source application, but they want a "company name" and what we do. Heh.

Aware of an existing docker open source project I could join?

**Comment by olivierdalang** [comment]
Actually I already opened a https://github.com/mla/pg_sample/pull/29 that does the build with github actions, which should work without any particular account.

**Comment by mla** [comment]
Ok, I think we're close @olivierdalang! Thank you for clearing that up.

I created the github account. Used username mla12 since they didn't like mla. 
Have successfully built and pushed to dockerhub with:

```
sudo docker build . -t mla12/pg_sample
sudo docker push mla12/pg_sample:latest
```

I see it in dockerhub. I was getting an error about file not found when I tried to run it. See my change to Dockerfile. I changed ENTRYPOINT to use fully qualified path. That seemed to fix it but idk if that's right or not.

I *think* the latest github workflow docker publish just worked.

Let me know how things look from your perspective?

**Comment by mla** [comment]
Made a few more changes. Modified Dockefile to use cpanm and the main image perl (rather than system perl).

I changed the readme a bit to make it more generic and use placeholders.

I moved the note about docker image publishing into a new CONTRIBUTING.md.

Let me know if you see any issues with those changes.
